/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 26
#line 1 "syntax.leg"

#include <stdio.h>
#include <stdlib.h>
#include "tagtuple.h"
#include "utils.h"
#include "syntax.h"

typedef struct {
    int line;
    union {
        tag_tuple * tag_tuple;
        char *text;
    } value;
} parse_result;

typedef struct {
    int current_line;
    int lines_read;
    int interactive;
    FILE *stream;
    char last_read_char[2];
    parse_output output;
} state;

#define YYSTYPE parse_result
#define YY_CTX_LOCAL
#define YY_CTX_MEMBERS state state;

#define YY_INPUT(yy, buf, result, max_size)             \
  {                                                     \
    int yyc= getc(yy->state.stream);                    \
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);        \
    yy->state.lines_read += yyc == '\n'                 \
    yyprintf((stderr, "<%c>", yyc));                    \
    yy->state.last_read_char[0] = yyc;                  \
  }

static parse_result result(tag_tuple * tag_tuple) {
    parse_result result;
    result.line = tag_tuple != NULL ? tag_tuple->line_number : -1;
    result.value.tag_tuple = tag_tuple;
    return result;
}

static parse_result result_arg_list(tag_tuple *head, parse_result *tail) {
    tag_tuple * previous_head = tail != NULL ? tail->value.tag_tuple : NULL;
    if (head != NULL)
        head->next = previous_head;
    else
        head = previous_head;
    return result(head);
}

static parse_result result_text(int line, char *text) {
    parse_result result;
    result.line = line;
    result.value.text = clone_string(text);
    return result;
}

static parse_result result_line(state *state) {
    parse_result result;
    result.line = state->current_line;
    result.value.tag_tuple = NULL;
    result.value.text = NULL;
    return result;
}

static void error(state *state, parse_error_code code, operation op, char *text) {
    if (state->output.error_code != PARSE_ERROR_OK)
        return; 
    tag_tuple * const root = state->output.error_code == PARSE_ERROR_OK ? state->output.value.root : NULL;
    state->output.error_code = code; 
    state->output.value.error.op = op;
    if (text != NULL) {
        int len = sizeof(state->output.value.error.text) - 1;
        strncpy(state->output.value.error.text, text, len);
        state->output.value.error.text[len] = '\0';
    } else {
        state->output.value.error.text[0] = '\0';
    }
    state->output.value.error.line = state->lines_read + 1;
    state->output.value.error.leftover = root;
    if (root != NULL)
        fprintf(stderr, "LEFTOVER\n");
}

static void output(state *state, tag_tuple * root) {
    if (state->output.error_code == PARSE_ERROR_OK)
        release_tagtuple(state->output.value.root);
    else     
        release_tagtuple(state->output.value.error.leftover);
    state->output.error_code = PARSE_ERROR_OK;
    state->output.value.root = root;
}
#define WHITE_SPACE(X) ((X) == ' ' || (X) == '\t' || (X) == '\r' || (X) == '\n')

static void unexpexted_character_error(state *state, char *buf, int pos, int len) {
  // if (pos > 0 && pos < len && !WHITE_SPACE(buf[pos - 1]))  
  //      state->last_read_char[0] = buf[pos - 1];
    if (state->last_read_char[0] <= 0)
        error(state, PARSE_ERROR_END_OF_INPUT, 0, "");    
    else
        error(state, PARSE_ERROR_UNEXPECTED_CHAR, 0, state->last_read_char);
}


#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_SOME(yycontext *yy); /* 26 */
YY_RULE(int) yy_EOL(yycontext *yy); /* 25 */
YY_RULE(int) yy_Char(yycontext *yy); /* 24 */
YY_RULE(int) yy_QUOTES(yycontext *yy); /* 23 */
YY_RULE(int) yy_COMMA(yycontext *yy); /* 22 */
YY_RULE(int) yy_ArgList(yycontext *yy); /* 21 */
YY_RULE(int) yy_TAG(yycontext *yy); /* 20 */
YY_RULE(int) yy_CLOSE_BRACKET(yycontext *yy); /* 19 */
YY_RULE(int) yy_OPEN_BRACKET(yycontext *yy); /* 18 */
YY_RULE(int) yy_CLOSE(yycontext *yy); /* 17 */
YY_RULE(int) yy_Arguments(yycontext *yy); /* 16 */
YY_RULE(int) yy_OPEN(yycontext *yy); /* 15 */
YY_RULE(int) yy_TAG_OR_EMPTY(yycontext *yy); /* 14 */
YY_RULE(int) yy_String(yycontext *yy); /* 13 */
YY_RULE(int) yy_NUMBER(yycontext *yy); /* 12 */
YY_RULE(int) yy_DIVIDE(yycontext *yy); /* 11 */
YY_RULE(int) yy_TIMES(yycontext *yy); /* 10 */
YY_RULE(int) yy_Value(yycontext *yy); /* 9 */
YY_RULE(int) yy_MINUS(yycontext *yy); /* 8 */
YY_RULE(int) yy_PLUS(yycontext *yy); /* 7 */
YY_RULE(int) yy_Product(yycontext *yy); /* 6 */
YY_RULE(int) yy_Sum(yycontext *yy); /* 5 */
YY_RULE(int) yy_EOF(yycontext *yy); /* 4 */
YY_RULE(int) yy_Expr(yycontext *yy); /* 3 */
YY_RULE(int) yy__(yycontext *yy); /* 2 */
YY_RULE(int) yy_Stmt(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_EOL(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_EOL\n"));
  {
#line 166
   yy->state.current_line++; printf("line %d\n", yy->state.current_line);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_OPEN(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_OPEN\n"));
  {
#line 159
   __ = s; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}
YY_ACTION(void) yy_1_DIVIDE(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_DIVIDE\n"));
  {
#line 158
   __ = s; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}
YY_ACTION(void) yy_1_TIMES(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_TIMES\n"));
  {
#line 157
   __ = s; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}
YY_ACTION(void) yy_1_MINUS(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_MINUS\n"));
  {
#line 156
   __ = s; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}
YY_ACTION(void) yy_1_PLUS(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_PLUS\n"));
  {
#line 155
   __ = s; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}
YY_ACTION(void) yy_1_SOME(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_SOME\n"));
  {
#line 154
   __ = result_line(&yy->state); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_TAG_OR_EMPTY(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_TAG_OR_EMPTY\n"));
  {
#line 153
   __ = result_text(yy->state.current_line, ""); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_TAG(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_TAG\n"));
  {
#line 152
   __ = result_text(s.line, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}
YY_ACTION(void) yy_1_NUMBER(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_NUMBER\n"));
  {
#line 151
   __ = result(make_number(s.line, atof(yytext))); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}
YY_ACTION(void) yy_1_String(yycontext *yy, char *yytext, int yyleng)
{
#define q yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_String\n"));
  {
#line 145
  __ = result(make_string(q.line, yytext)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef q
}
YY_ACTION(void) yy_2_ArgList(yycontext *yy, char *yytext, int yyleng)
{
#define l yy->__val[-1]
#define e yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_ArgList\n"));
  {
#line 142
   __ = result_arg_list(e.value.tag_tuple, NULL);;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef l
#undef e
}
YY_ACTION(void) yy_1_ArgList(yycontext *yy, char *yytext, int yyleng)
{
#define l yy->__val[-1]
#define e yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_ArgList\n"));
  {
#line 141
   __ = result_arg_list(e.value.tag_tuple, &l);;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef l
#undef e
}
YY_ACTION(void) yy_2_Arguments(yycontext *yy, char *yytext, int yyleng)
{
#define a yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Arguments\n"));
  {
#line 136
   __ = result_arg_list(NULL, NULL);;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef a
}
YY_ACTION(void) yy_1_Arguments(yycontext *yy, char *yytext, int yyleng)
{
#define a yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Arguments\n"));
  {
#line 135
   __ = a; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef a
}
YY_ACTION(void) yy_5_Value(yycontext *yy, char *yytext, int yyleng)
{
#define a yy->__val[-1]
#define t yy->__val[-2]
#define s yy->__val[-3]
#define i yy->__val[-4]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_Value\n"));
  {
#line 133
   __ = result(make_tag(t.line, t.value.text, 1)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef a
#undef t
#undef s
#undef i
}
YY_ACTION(void) yy_4_Value(yycontext *yy, char *yytext, int yyleng)
{
#define a yy->__val[-1]
#define t yy->__val[-2]
#define s yy->__val[-3]
#define i yy->__val[-4]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Value\n"));
  {
#line 132
   __ = result(make_block(t.line, t.value.text, 1, a.value.tag_tuple)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef a
#undef t
#undef s
#undef i
}
YY_ACTION(void) yy_3_Value(yycontext *yy, char *yytext, int yyleng)
{
#define a yy->__val[-1]
#define t yy->__val[-2]
#define s yy->__val[-3]
#define i yy->__val[-4]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Value\n"));
  {
#line 131
   __ = result(make_tuple(t.line, t.value.text, 1, a.value.tag_tuple)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef a
#undef t
#undef s
#undef i
}
YY_ACTION(void) yy_2_Value(yycontext *yy, char *yytext, int yyleng)
{
#define a yy->__val[-1]
#define t yy->__val[-2]
#define s yy->__val[-3]
#define i yy->__val[-4]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Value\n"));
  {
#line 130
   __ = s; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef a
#undef t
#undef s
#undef i
}
YY_ACTION(void) yy_1_Value(yycontext *yy, char *yytext, int yyleng)
{
#define a yy->__val[-1]
#define t yy->__val[-2]
#define s yy->__val[-3]
#define i yy->__val[-4]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Value\n"));
  {
#line 129
   __ = i; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef a
#undef t
#undef s
#undef i
}
YY_ACTION(void) yy_3_Product(yycontext *yy, char *yytext, int yyleng)
{
#define r yy->__val[-1]
#define op yy->__val[-2]
#define l yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Product\n"));
  {
#line 127
   __ = l; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef r
#undef op
#undef l
}
YY_ACTION(void) yy_2_Product(yycontext *yy, char *yytext, int yyleng)
{
#define r yy->__val[-1]
#define op yy->__val[-2]
#define l yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Product\n"));
  {
#line 126
   l = result(make_exp(op.line, OP_DIV, l.value.tag_tuple, r.value.tag_tuple));  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef r
#undef op
#undef l
}
YY_ACTION(void) yy_1_Product(yycontext *yy, char *yytext, int yyleng)
{
#define r yy->__val[-1]
#define op yy->__val[-2]
#define l yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Product\n"));
  {
#line 124
   l = result(make_exp(op.line, OP_MUL, l.value.tag_tuple, r.value.tag_tuple));  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef r
#undef op
#undef l
}
YY_ACTION(void) yy_3_Sum(yycontext *yy, char *yytext, int yyleng)
{
#define r yy->__val[-1]
#define op yy->__val[-2]
#define l yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Sum\n"));
  {
#line 120
   __ = l; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef r
#undef op
#undef l
}
YY_ACTION(void) yy_2_Sum(yycontext *yy, char *yytext, int yyleng)
{
#define r yy->__val[-1]
#define op yy->__val[-2]
#define l yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Sum\n"));
  {
#line 119
   l = result(make_exp(op.line, OP_SUB, l.value.tag_tuple, r.value.tag_tuple)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef r
#undef op
#undef l
}
YY_ACTION(void) yy_1_Sum(yycontext *yy, char *yytext, int yyleng)
{
#define r yy->__val[-1]
#define op yy->__val[-2]
#define l yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Sum\n"));
  {
#line 117
   l = result(make_exp(op.line, OP_ADD, l.value.tag_tuple, r.value.tag_tuple)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef r
#undef op
#undef l
}
YY_ACTION(void) yy_1_Expr(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Expr\n"));
  {
#line 113
   __ = s; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}
YY_ACTION(void) yy_2_Stmt(yycontext *yy, char *yytext, int yyleng)
{
#define e yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Stmt\n"));
  {
#line 111
   error(&yy->state, PARSE_ERROR_NEAR, 0, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef e
}
YY_ACTION(void) yy_1_Stmt(yycontext *yy, char *yytext, int yyleng)
{
#define e yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Stmt\n"));
  {
#line 110
   output(&yy->state, e.value.tag_tuple); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef e
}

YY_RULE(int) yy_SOME(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "SOME"));
  {  int yypos2= yy->__pos, yythunkpos2= yy->__thunkpos;  if (!yymatchDot(yy)) goto l1;  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;
  }  if (!yy__(yy)) goto l1;  yyDo(yy, yy_1_SOME, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "SOME", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SOME", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EOL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EOL"));
  {  int yypos4= yy->__pos, yythunkpos4= yy->__thunkpos;  if (!yymatchChar(yy, '\n')) goto l5;  goto l4;
  l5:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchString(yy, "\r\n")) goto l6;  goto l4;
  l6:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchChar(yy, '\r')) goto l3;
  }
  l4:;	  yyDo(yy, yy_1_EOL, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", yy->__buf+yy->__pos));
  return 1;
  l3:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Char(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Char"));
  {  int yypos8= yy->__pos, yythunkpos8= yy->__thunkpos;  if (!yymatchChar(yy, '\\')) goto l9;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\204\000\000\000\000\000\000\070\146\100\124\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l9;  goto l8;
  l9:;	  yy->__pos= yypos8; yy->__thunkpos= yythunkpos8;  if (!yymatchChar(yy, '\\')) goto l10;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\017\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l10;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l10;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l10;  goto l8;
  l10:;	  yy->__pos= yypos8; yy->__thunkpos= yythunkpos8;  if (!yymatchChar(yy, '\\')) goto l11;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l11;
  {  int yypos12= yy->__pos, yythunkpos12= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l12;  goto l13;
  l12:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;
  }
  l13:;	  goto l8;
  l11:;	  yy->__pos= yypos8; yy->__thunkpos= yythunkpos8;
  {  int yypos14= yy->__pos, yythunkpos14= yy->__thunkpos;  if (!yymatchChar(yy, '\\')) goto l14;  goto l7;
  l14:;	  yy->__pos= yypos14; yy->__thunkpos= yythunkpos14;
  }
  {  int yypos15= yy->__pos, yythunkpos15= yy->__thunkpos;  if (!yy_EOL(yy)) goto l16;  goto l15;
  l16:;	  yy->__pos= yypos15; yy->__thunkpos= yythunkpos15;  if (!yymatchDot(yy)) goto l7;
  }
  l15:;	
  }
  l8:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Char", yy->__buf+yy->__pos));
  return 1;
  l7:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Char", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_QUOTES(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "QUOTES"));  if (!yymatchChar(yy, '"')) goto l17;  if (!yy__(yy)) goto l17;
  yyprintf((stderr, "  ok   %s @ %s\n", "QUOTES", yy->__buf+yy->__pos));
  return 1;
  l17:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "QUOTES", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_COMMA(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "COMMA"));  if (!yymatchChar(yy, ',')) goto l18;  if (!yy__(yy)) goto l18;
  yyprintf((stderr, "  ok   %s @ %s\n", "COMMA", yy->__buf+yy->__pos));
  return 1;
  l18:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COMMA", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ArgList(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "ArgList"));
  {  int yypos20= yy->__pos, yythunkpos20= yy->__thunkpos;  if (!yy_Expr(yy)) goto l21;  yyDo(yy, yySet, -2, 0);  if (!yy_COMMA(yy)) goto l21;  if (!yy_ArgList(yy)) goto l23;  yyDo(yy, yySet, -1, 0);  goto l22;
  l23:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
   error(&yy->state, PARSE_ERROR_MISSING_ARGUMENT, 0, yy->state.last_read_char);
#undef yytext
#undef yyleng
  }  goto l21;
  l22:;	  yyDo(yy, yy_1_ArgList, yy->__begin, yy->__end);  goto l20;
  l21:;	  yy->__pos= yypos20; yy->__thunkpos= yythunkpos20;  if (!yy_Expr(yy)) goto l19;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_2_ArgList, yy->__begin, yy->__end);
  }
  l20:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "ArgList", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l19:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ArgList", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_TAG(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "TAG"));  if (!yy_SOME(yy)) goto l24;  yyDo(yy, yySet, -1, 0);  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l24;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l24;
  l25:;	
  {  int yypos26= yy->__pos, yythunkpos26= yy->__thunkpos;
  {  int yypos27= yy->__pos, yythunkpos27= yy->__thunkpos;  if (!yymatchChar(yy, '.')) goto l28;  goto l27;
  l28:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l26;
  }
  l27:;	  goto l25;
  l26:;	  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l24;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l24;  yyDo(yy, yy_1_TAG, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "TAG", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l24:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TAG", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CLOSE_BRACKET(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CLOSE_BRACKET"));  if (!yymatchChar(yy, '}')) goto l29;  if (!yy__(yy)) goto l29;
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE_BRACKET", yy->__buf+yy->__pos));
  return 1;
  l29:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE_BRACKET", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OPEN_BRACKET(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OPEN_BRACKET"));  if (!yymatchChar(yy, '{')) goto l30;  if (!yy__(yy)) goto l30;
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN_BRACKET", yy->__buf+yy->__pos));
  return 1;
  l30:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN_BRACKET", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CLOSE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "CLOSE"));  if (!yy_SOME(yy)) goto l31;  yyDo(yy, yySet, 0, 0);  if (!yymatchChar(yy, ')')) goto l31;  if (!yy__(yy)) goto l31;
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l31:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Arguments(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "Arguments"));
  {  int yypos33= yy->__pos, yythunkpos33= yy->__thunkpos;  if (!yy_ArgList(yy)) goto l34;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_Arguments, yy->__begin, yy->__end);  goto l33;
  l34:;	  yy->__pos= yypos33; yy->__thunkpos= yythunkpos33;  if (!yy__(yy)) goto l32;  yyDo(yy, yy_2_Arguments, yy->__begin, yy->__end);
  }
  l33:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Arguments", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l32:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Arguments", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OPEN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "OPEN"));  if (!yy_SOME(yy)) goto l35;  yyDo(yy, yySet, -1, 0);  if (!yymatchChar(yy, '(')) goto l35;  if (!yy__(yy)) goto l35;  yyDo(yy, yy_1_OPEN, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l35:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_TAG_OR_EMPTY(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "TAG_OR_EMPTY"));
  {  int yypos37= yy->__pos, yythunkpos37= yy->__thunkpos;  if (!yy_TAG(yy)) goto l38;  goto l37;
  l38:;	  yy->__pos= yypos37; yy->__thunkpos= yythunkpos37;  if (!yy__(yy)) goto l36;  yyDo(yy, yy_1_TAG_OR_EMPTY, yy->__begin, yy->__end);
  }
  l37:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "TAG_OR_EMPTY", yy->__buf+yy->__pos));
  return 1;
  l36:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TAG_OR_EMPTY", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_String(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "String"));  if (!yy_QUOTES(yy)) goto l39;  yyDo(yy, yySet, -1, 0);  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l39;
#undef yytext
#undef yyleng
  }
  l40:;	
  {  int yypos41= yy->__pos, yythunkpos41= yy->__thunkpos;
  {  int yypos42= yy->__pos, yythunkpos42= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l42;  goto l41;
  l42:;	  yy->__pos= yypos42; yy->__thunkpos= yythunkpos42;
  }  if (!yy_Char(yy)) goto l41;  goto l40;
  l41:;	  yy->__pos= yypos41; yy->__thunkpos= yythunkpos41;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l39;
#undef yytext
#undef yyleng
  }  if (!yy_QUOTES(yy)) goto l39;  if (!yy__(yy)) goto l39;  yyDo(yy, yy_1_String, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "String", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l39:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "String", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NUMBER(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "NUMBER"));  if (!yy_SOME(yy)) goto l43;  yyDo(yy, yySet, -1, 0);  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l43;
#undef yytext
#undef yyleng
  }
  {  int yypos44= yy->__pos, yythunkpos44= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l44;  goto l45;
  l44:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;
  }
  l45:;	  if (!yy__(yy)) goto l43;
  {  int yypos46= yy->__pos, yythunkpos46= yy->__thunkpos;
  l48:;	
  {  int yypos49= yy->__pos, yythunkpos49= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l49;  goto l48;
  l49:;	  yy->__pos= yypos49; yy->__thunkpos= yythunkpos49;
  }  if (!yymatchChar(yy, '.')) goto l47;
  l50:;	
  {  int yypos51= yy->__pos, yythunkpos51= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l51;  goto l50;
  l51:;	  yy->__pos= yypos51; yy->__thunkpos= yythunkpos51;
  }  goto l46;
  l47:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l43;
  l52:;	
  {  int yypos53= yy->__pos, yythunkpos53= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l53;  goto l52;
  l53:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;
  }
  }
  l46:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l43;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l43;  yyDo(yy, yy_1_NUMBER, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "NUMBER", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l43:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUMBER", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_DIVIDE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "DIVIDE"));  if (!yy_SOME(yy)) goto l54;  yyDo(yy, yySet, -1, 0);  if (!yymatchChar(yy, '/')) goto l54;  if (!yy__(yy)) goto l54;  yyDo(yy, yy_1_DIVIDE, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "DIVIDE", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l54:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DIVIDE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_TIMES(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "TIMES"));  if (!yy_SOME(yy)) goto l55;  yyDo(yy, yySet, -1, 0);  if (!yymatchChar(yy, '*')) goto l55;  if (!yy__(yy)) goto l55;  yyDo(yy, yy_1_TIMES, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "TIMES", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l55:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TIMES", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Value(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 4, 0);
  yyprintf((stderr, "%s\n", "Value"));
  {  int yypos57= yy->__pos, yythunkpos57= yy->__thunkpos;  if (!yy_NUMBER(yy)) goto l58;  yyDo(yy, yySet, -4, 0);  yyDo(yy, yy_1_Value, yy->__begin, yy->__end);  goto l57;
  l58:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yy_String(yy)) goto l59;  yyDo(yy, yySet, -3, 0);  yyDo(yy, yy_2_Value, yy->__begin, yy->__end);  goto l57;
  l59:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yy_TAG_OR_EMPTY(yy)) goto l60;  yyDo(yy, yySet, -2, 0);  if (!yy_OPEN(yy)) goto l60;  if (!yy_Arguments(yy)) goto l60;  yyDo(yy, yySet, -1, 0);  if (!yy_CLOSE(yy)) goto l60;  yyDo(yy, yy_3_Value, yy->__begin, yy->__end);  goto l57;
  l60:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yy_TAG_OR_EMPTY(yy)) goto l61;  yyDo(yy, yySet, -2, 0);  if (!yy_OPEN_BRACKET(yy)) goto l61;  if (!yy_Arguments(yy)) goto l61;  yyDo(yy, yySet, -1, 0);  if (!yy_CLOSE_BRACKET(yy)) goto l61;  yyDo(yy, yy_4_Value, yy->__begin, yy->__end);  goto l57;
  l61:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  if (!yy_TAG(yy)) goto l56;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_5_Value, yy->__begin, yy->__end);
  }
  l57:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Value", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 4, 0);
  return 1;
  l56:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Value", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_MINUS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "MINUS"));  if (!yy_SOME(yy)) goto l62;  yyDo(yy, yySet, -1, 0);  if (!yymatchChar(yy, '-')) goto l62;  if (!yy__(yy)) goto l62;  yyDo(yy, yy_1_MINUS, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "MINUS", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l62:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MINUS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PLUS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "PLUS"));  if (!yy_SOME(yy)) goto l63;  yyDo(yy, yySet, -1, 0);  if (!yymatchChar(yy, '+')) goto l63;  if (!yy__(yy)) goto l63;  yyDo(yy, yy_1_PLUS, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "PLUS", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l63:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PLUS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Product(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "Product"));  if (!yy_Value(yy)) goto l64;  yyDo(yy, yySet, -3, 0);
  l65:;	
  {  int yypos66= yy->__pos, yythunkpos66= yy->__thunkpos;
  {  int yypos67= yy->__pos, yythunkpos67= yy->__thunkpos;  if (!yy_TIMES(yy)) goto l68;  yyDo(yy, yySet, -2, 0);  if (!yy_Value(yy)) goto l70;  yyDo(yy, yySet, -1, 0);  goto l69;
  l70:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
   error(&yy->state, PARSE_ERROR_MISSING_OPERAND, OP_MUL, NULL);
#undef yytext
#undef yyleng
  }  goto l68;
  l69:;	  yyDo(yy, yy_1_Product, yy->__begin, yy->__end);  goto l67;
  l68:;	  yy->__pos= yypos67; yy->__thunkpos= yythunkpos67;  if (!yy_DIVIDE(yy)) goto l66;  yyDo(yy, yySet, -2, 0);  if (!yy_Value(yy)) goto l72;  yyDo(yy, yySet, -1, 0);  goto l71;
  l72:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
   error(&yy->state, PARSE_ERROR_MISSING_OPERAND, OP_DIV, NULL);
#undef yytext
#undef yyleng
  }  goto l66;
  l71:;	  yyDo(yy, yy_2_Product, yy->__begin, yy->__end);
  }
  l67:;	  goto l65;
  l66:;	  yy->__pos= yypos66; yy->__thunkpos= yythunkpos66;
  }  yyDo(yy, yy_3_Product, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Product", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l64:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Product", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Sum(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "Sum"));  if (!yy_Product(yy)) goto l73;  yyDo(yy, yySet, -3, 0);
  l74:;	
  {  int yypos75= yy->__pos, yythunkpos75= yy->__thunkpos;
  {  int yypos76= yy->__pos, yythunkpos76= yy->__thunkpos;  if (!yy_PLUS(yy)) goto l77;  yyDo(yy, yySet, -2, 0);  if (!yy_Product(yy)) goto l79;  yyDo(yy, yySet, -1, 0);  goto l78;
  l79:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
   error(&yy->state, PARSE_ERROR_MISSING_OPERAND, OP_ADD, NULL);
#undef yytext
#undef yyleng
  }  goto l77;
  l78:;	  yyDo(yy, yy_1_Sum, yy->__begin, yy->__end);  goto l76;
  l77:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yy_MINUS(yy)) goto l75;  yyDo(yy, yySet, -2, 0);  if (!yy_Product(yy)) goto l81;  yyDo(yy, yySet, -1, 0);  goto l80;
  l81:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
   error(&yy->state, PARSE_ERROR_MISSING_OPERAND, OP_SUB, NULL);
#undef yytext
#undef yyleng
  }  goto l75;
  l80:;	  yyDo(yy, yy_2_Sum, yy->__begin, yy->__end);
  }
  l76:;	  goto l74;
  l75:;	  yy->__pos= yypos75; yy->__thunkpos= yythunkpos75;
  }  yyDo(yy, yy_3_Sum, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Sum", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l73:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Sum", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EOF(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EOF"));
  {  int yypos85= yy->__pos, yythunkpos85= yy->__thunkpos;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(yy->state.interactive)) goto l86;
#undef yytext
#undef yyleng
  }  if (!yymatchString(yy, ";;;")) goto l86;  if (!yy_EOL(yy)) goto l86;  goto l85;
  l86:;	  yy->__pos= yypos85; yy->__thunkpos= yythunkpos85;
  {  int yypos87= yy->__pos, yythunkpos87= yy->__thunkpos;  if (!yymatchDot(yy)) goto l87;  goto l84;
  l87:;	  yy->__pos= yypos87; yy->__thunkpos= yythunkpos87;
  }
  }
  l85:;	  goto l83;
  l84:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
   unexpexted_character_error(&yy->state, yy->__buf, yy->__pos, yy->__buflen); ;
#undef yytext
#undef yyleng
  }  goto l82;
  l83:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "EOF", yy->__buf+yy->__pos));
  return 1;
  l82:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOF", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Expr(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "Expr"));  if (!yy_Sum(yy)) goto l88;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_Expr, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Expr", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l88:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Expr", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy__(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "_"));
  l90:;	
  {  int yypos91= yy->__pos, yythunkpos91= yy->__thunkpos;
  {  int yypos92= yy->__pos, yythunkpos92= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l93;  goto l92;
  l93:;	  yy->__pos= yypos92; yy->__thunkpos= yythunkpos92;  if (!yy_EOL(yy)) goto l91;
  }
  l92:;	  goto l90;
  l91:;	  yy->__pos= yypos91; yy->__thunkpos= yythunkpos91;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_Stmt(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "Stmt"));
  {  int yypos95= yy->__pos, yythunkpos95= yy->__thunkpos;  if (!yy__(yy)) goto l96;  if (!yy_Expr(yy)) goto l96;  yyDo(yy, yySet, -1, 0);  if (!yy_EOF(yy)) goto l96;  yyDo(yy, yy_1_Stmt, yy->__begin, yy->__end);  goto l95;
  l96:;	  yy->__pos= yypos95; yy->__thunkpos= yythunkpos95;
  l97:;	
  {  int yypos98= yy->__pos, yythunkpos98= yy->__thunkpos;
  {  int yypos99= yy->__pos, yythunkpos99= yy->__thunkpos;  if (!yy_EOF(yy)) goto l99;  goto l98;
  l99:;	  yy->__pos= yypos99; yy->__thunkpos= yythunkpos99;
  }  if (!yymatchDot(yy)) goto l98;  goto l97;
  l98:;	  yy->__pos= yypos98; yy->__thunkpos= yythunkpos98;
  }  if (!yy_EOF(yy)) goto l94;  yyDo(yy, yy_2_Stmt, yy->__begin, yy->__end);
  }
  l95:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Stmt", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l94:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Stmt", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_Stmt);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 168 "syntax.leg"


static void init_iteractive_state(state *state) {
    state->interactive = 1;
    state->stream = stdin;
}

void tagtuple_interactive(void (*run)(parse_output output)) {
    if (run == NULL)
        return;
    yycontext ctx;
    memset(&ctx, 0, sizeof(yycontext));
    init_iteractive_state(&ctx.state);
    while (yyparse(&ctx)) {
        const parse_output output = ctx.state.output;
        run(output);
        if (feof(ctx.state.stream))
            break;
        memset(&ctx.state, 0, sizeof(state));
        init_iteractive_state(&ctx.state);
    }
    yyrelease(&ctx);
}

parse_output tagtuple_parse(FILE *stream) {
    yycontext ctx;
    memset(&ctx, 0, sizeof(yycontext));
    ctx.state.interactive = 0;
    ctx.state.stream = stream;
    yyparse(&ctx);
    const parse_output output = ctx.state.output;
    yyrelease(&ctx);
    return output;
}

